project:
  type: website

website:
  title: "ShineWook"
  site-url: https://shinewook.netlify.app/
  description: ""
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ruddnr
  google-analytics: G-J7SQX0QB2L

format:
  html:
    theme: litera
    css: styles.css
    
comments:
  giscus:
    repo: ruddnr/jk_blog
    
execute:
  freeze: auto

editor: visual



