project:
  type: website

website:
  title: "JKW"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ruddnr

format:
  html:
    theme: litera
    css: styles.css
    
comments:
  giscus:
    repo: ruddnr/jk_blog

editor: visual

