project:
  type: website

website:
  title: "jk_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css
    
comments:
  giscus:
    repo: ruddnr/jk_blog

editor: visual

